/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacomercial;

import Classe.RetornoDoDAO;
import DAO.CaixaDAO;
import DAO.PedidoDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo
 */
public class FrenteDeCaixa extends javax.swing.JFrame {
    
     CaixaDAO caixaDAO = new CaixaDAO("scv","root");
  
    /**
     * Creates new form FrenteDeCaixa
     */
    public FrenteDeCaixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Frente de Caixa");

        btnIniciarPedido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIniciarPedido.setText("Iniciar Pedido");
        btnIniciarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIniciarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIniciarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPedidoActionPerformed
       //Verifica se o caixa esta aberto
        RetornoDoDAO  respostaSeTemCaixaAberto;
        respostaSeTemCaixaAberto = caixaDAO.temCaixaAberto();
        if(!respostaSeTemCaixaAberto.executadoComSucesso){
            JOptionPane.showMessageDialog(null,respostaSeTemCaixaAberto.mensagem,"Erro",JOptionPane.ERROR_MESSAGE); 
        }
        else{
        
        //tenho que verificar se foi executado com sucesso
         if(!respostaSeTemCaixaAberto.valorDoRetornoBooleano){
            JOptionPane.showMessageDialog(null,respostaSeTemCaixaAberto.mensagem,"Erro",JOptionPane.ERROR_MESSAGE); 
        }else{
        RetornoDoDAO respostaNumeroDoCaixa = caixaDAO.numeroDoCaixaAberto();
        if(respostaNumeroDoCaixa.executadoComSucesso){
            int numeroDoCaixaAberto  = respostaNumeroDoCaixa.valorRetornadoInteiro;
            // Se tiver pedido aberto vai para ele. Caso contrário abre um
            PedidoDAO dao = new PedidoDAO("scv","root");
            int num = 0;
            int aberto = 0;
            try {
                aberto = dao.pedidosEmAberto();
            } catch (SQLException ex) {
            Logger.getLogger(FrenteDeCaixa.class.getName()).log(Level.SEVERE, null, ex);
            }
        if(aberto == 0){
            num = dao.inicia();
        }else{
            try {
                num = dao.pegaPedidoAberto().getCodigoDoPedido();
            } catch (SQLException ex) {
                Logger.getLogger(FrenteDeCaixa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        FrmVendas frm = new FrmVendas(num,numeroDoCaixaAberto);
        frm.setVisible(true);
        }        
         }    }
    }//GEN-LAST:event_btnIniciarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrenteDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrenteDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrenteDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrenteDeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrenteDeCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarPedido;
    // End of variables declaration//GEN-END:variables
}
