/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacomercial;

import Classe.RetornoDoDAO;
import DAO.CaixaDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCadastraCliente = new javax.swing.JMenuItem();
        menuCadastraProduto = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuAbrirCaixa = new javax.swing.JMenuItem();
        menuFecharCaixa = new javax.swing.JMenuItem();
        menuDeposito = new javax.swing.JMenuItem();
        menuSuprimento = new javax.swing.JMenuItem();
        menuUltimosCaixas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de vendas");

        jMenu1.setText("Arquivo");

        menuCadastraCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        menuCadastraCliente.setText("Cadastro de Clientes");
        menuCadastraCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastraClienteActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastraCliente);

        menuCadastraProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        menuCadastraProduto.setText("Cadastro de Produtos");
        menuCadastraProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastraProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastraProduto);

        menuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimentação");

        menuAbrirCaixa.setText("Abrir o Caixa");
        menuAbrirCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirCaixaActionPerformed(evt);
            }
        });
        jMenu2.add(menuAbrirCaixa);

        menuFecharCaixa.setText("Fechar o Caixa");
        jMenu2.add(menuFecharCaixa);

        menuDeposito.setText("Depósito");
        jMenu2.add(menuDeposito);

        menuSuprimento.setText("Suprimento");
        jMenu2.add(menuSuprimento);

        menuUltimosCaixas.setText("Ultimos caixas");
        jMenu2.add(menuUltimosCaixas);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastraClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastraClienteActionPerformed
        FrmCliente frmCliente = new FrmCliente();
        frmCliente.setVisible(true);
    
    }//GEN-LAST:event_menuCadastraClienteActionPerformed

    private void menuCadastraProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastraProdutoActionPerformed
       FrmProduto frmProduto = new FrmProduto();
       frmProduto.setVisible(true);
    }//GEN-LAST:event_menuCadastraProdutoActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
       this.dispose();
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuAbrirCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirCaixaActionPerformed
        CaixaDAO caixaDAO = new CaixaDAO("scv","root");
        RetornoDoDAO respostaNumeroDoNovoCaixa;
        respostaNumeroDoNovoCaixa = caixaDAO.numeroDoNovoCaixa();
        if(respostaNumeroDoNovoCaixa.executadoComSucesso){
            int numeroDoNovoCaixa = respostaNumeroDoNovoCaixa.valorRetornadoInteiro;
            RetornoDoDAO respostaSeTemCaixaAberto = caixaDAO.temCaixaAberto();
            if(respostaSeTemCaixaAberto.executadoComSucesso){
                if(!respostaSeTemCaixaAberto.valorDoRetornoBooleano){
                    FrmAbrirCaixa frm = new FrmAbrirCaixa(numeroDoNovoCaixa);
                    frm.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(null,respostaSeTemCaixaAberto.mensagem,"Caixa",JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null,respostaSeTemCaixaAberto.mensagem,"Caixa",JOptionPane.ERROR_MESSAGE);
        }
        }else{
            JOptionPane.showMessageDialog(null,respostaNumeroDoNovoCaixa.mensagem,"Caixa",JOptionPane.ERROR_MESSAGE);
        }
              
    }//GEN-LAST:event_menuAbrirCaixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAbrirCaixa;
    private javax.swing.JMenuItem menuCadastraCliente;
    private javax.swing.JMenuItem menuCadastraProduto;
    private javax.swing.JMenuItem menuDeposito;
    private javax.swing.JMenuItem menuFecharCaixa;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuSuprimento;
    private javax.swing.JMenuItem menuUltimosCaixas;
    // End of variables declaration//GEN-END:variables
}
