/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacomercial;

import Classe.ItensDoPedido;
import Classe.Produto;
import Classe.ViewItensDoPedido;
import DAO.ItensDoPedidoDAO;
import DAO.ViewItensDoPedidoDAO;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo
 */
public class FrmVendasProduto extends javax.swing.JFrame {

    /**
     * Creates new form FrmVendasProduto
     */
    Produto produto = new Produto();
    FrmVendas frmVendas;
    int numPedido;
    ViewItensDoPedido viw;
    // tipo de operação 1 para Inserir vendas e 2 para atualizar
    private int tipoDeOperacaoCRUD;
    
    private static final NumberFormat FORMAT = NumberFormat.getCurrencyInstance();
    
    public FrmVendasProduto(Produto produto,FrmVendas frmVendas,int numPedido) {
        initComponents();
        this.produto = produto;
        this.txtNomeDoProduto.setText(produto.getNomeDoProduto());
        this.txtPrecoDoProduto.setText(FORMAT.format(produto.getPrecoDoProduto()));
        this.txtQuantidadeDeProdutos.setText("1");
        this.btnConfirmar.requestFocus();
        this.numPedido = numPedido;
        this.frmVendas = frmVendas;
        this.tipoDeOperacaoCRUD = 1;
    }
    
    public FrmVendasProduto(ViewItensDoPedido viw,FrmVendas frmVendas,int numPedido){
        initComponents();
        this.viw = viw;
        this.txtNomeDoProduto.setText(this.viw.getNomeDoProduto());
        this.txtPrecoDoProduto.setText(String.valueOf(this.viw.getValorUnitarioDoProduto()));
        this.txtQuantidadeDeProdutos.setText(String.valueOf(this.viw.getQuantidadeDeProdutos()));
        this.frmVendas = frmVendas;
        this.numPedido = numPedido;
        this.tipoDeOperacaoCRUD = 2; // Os dados serão atualizados
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomeDoProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrecoDoProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQuantidadeDeProdutos = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Produto");

        txtNomeDoProduto.setEditable(false);
        txtNomeDoProduto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Preço");

        txtPrecoDoProduto.setEditable(false);
        txtPrecoDoProduto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Quantidade");

        txtQuantidadeDeProdutos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        btnConfirmar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        btnConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnConfirmarKeyReleased(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtPrecoDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtQuantidadeDeProdutos))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtNomeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrecoDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantidadeDeProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        ItensDoPedido item = new ItensDoPedido();
        ItensDoPedidoDAO dao = new ItensDoPedidoDAO("scv","root");
        if(this.tipoDeOperacaoCRUD == 1){
           
            try {
                item.setCodigoDoItenDoPedido(dao.GetNextId("itensdopedido","cod"));
            } catch (SQLException ex) {
                Logger.getLogger(FrmVendasProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
            item.setCodigoDoPedido(this.numPedido);
            item.setCodigoDoProduto(produto.getCodigoDoProduto());
            item.setQuantidadeDeProdutos(Integer.parseInt(this.txtQuantidadeDeProdutos.getText()));
            item.setValorUnitarioDoProduto(produto.getPrecoDoProduto());
            dao.insere(item,this.numPedido);
        }
        else{
            item.setCodigoDoPedido(this.numPedido);
             item.setCodigoDoItenDoPedido(this.viw.getCodigoDosItensDoPedido());
            item.setCodigoDoProduto(this.viw.getCodigoDoProduto());
            item.setQuantidadeDeProdutos(Integer.parseInt(this.txtQuantidadeDeProdutos.getText()));
            item.setValorUnitarioDoProduto(this.viw.getValorUnitarioDoProduto());
            dao.atualiza(item);
        }
         frmVendas.lerItensDoPedido();
         this.dispose();
        
        
        /*
        
        
        frmVendas.carregarArea(produto.getCodProduto(),
               produto.getNome(),
               Double.parseDouble(this.edPreco.getText().trim()),
               Integer.parseInt(this.edQuantidade.getText().trim()));
               this.setVisible(false);
       frmVendas.total =  frmVendas.total +
                  Double.parseDouble(this.edPreco.getText().trim())*
                  Integer.parseInt(this.edQuantidade.getText().trim());
       frmVendas.atualizaProduto();*/
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnConfirmarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConfirmarKeyReleased
      JOptionPane.showMessageDialog(this,"OI !");
    }//GEN-LAST:event_btnConfirmarKeyReleased

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNomeDoProduto;
    private javax.swing.JTextField txtPrecoDoProduto;
    private javax.swing.JTextField txtQuantidadeDeProdutos;
    // End of variables declaration//GEN-END:variables
}
